### ISSUE TITLE
Proposal explainer is too "file" focused at the top

### ISSUE THREAD

**Issue by getify** [WICG/local-peer-to-peer#20]
It's certainly important that this proposed feature will allow file transfer P2P. But as there are quite a few non-file use cases being advanced for this API, I think the heavy use of "file" wording from the outset of the explainer is doing a disservice to future discussions about the proposal, by setting an unnecessarily narrow mental model for what's being discussed, only to later (by the end of the explainer) trying to broaden beyond files.

We already have discussion threads that seem to be spawned from that default assumption (this is mostly about files -- so why not use an established file sharing API like Web Share). I expect more of that to happen as this proposal matures and receives more attention/debate.

I would suggest we should re-arrange the wording (not add or remove, per se) such that we move from broader ideas (like "data transfer") down to more specific examples (like "file transfer") as you progress through the explainer.

**Comment by backkem** [comment]
Closed by #26.
